            - name: Checkmarx CxFlow Action
  # You may pin to the exact commit or the version.
  # uses: checkmarx-ts/checkmarx-cxflow-github-action@bfcb4817aadf2f63c9665ad901acfabd2410976e
  uses: checkmarx-ts/checkmarx-cxflow-github-action@v2.3
  with:
    # Provide Checkmarx URL
    checkmarx_url: http://sudhat-lt/ 
    # Select a Checkmarx Team
    team: # default is /CxServer
    # Provide Checkmarx Username
    checkmarx_username: sudha
    # Provide Checkmarx Password
    checkmarx_password: Ramji@2811
    # Provide Checkmarx Client Secret
    checkmarx_client_secret: # default is 
    # Select a Checkmarx Project
    project: CxSASt_github
  
  
    
